### PR TITLE
Added utilities for supporting rest and stream harvesting.

### PR DESCRIPTION
**Pull request by justinlittman**

### CODE REVIEW

**Comment by kerchner** [comment]
@justinlittman in requirements.txt, are you sure you want the warcprox requirement tied to that repo's master branch, which may be a moving target?  ```git+https://github.com/gwu-libraries/warcprox.git@master#egg=warcprox-gwu```

**Comment by kerchner** [comment]
@justinlittman I haven't read through all the code yet, but I ran unit tests and got two failures.  I am running this locally, not in a docker container.
```
======================================================================
FAIL: test_supervisor_start_and_stop (tests.sfmutils.test_supervisor.TestHarvestSupervisor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/home/kerchner/projects/sfm-utils/ENV/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/opt/home/kerchner/projects/sfm-utils/tests/sfmutils/test_supervisor.py", line 68, in test_supervisor_start_and_stop
    """.format(conf_path=conf_path, log_path=log_path), conf)
AssertionError: '[program:test_1]\ncommand=python /opt/sfm/test_harvester.py seed /tmp/tmpG4o1PQ/test_1.json --streaming --host test_host --username test_user --password test_password --routing-key harvest.start.test.test_search\nuser=justinlittman\nautostart=true\nautorestart=true\nstderr_logfile=/tmp/tmpbUl8xl/test_1.err.log\nstdout_logfile=/tmp/tmpbUl8xl/test_1.out.log\n' != '[program:test_1]\ncommand=python /opt/sfm/test_harvester.py seed /tmp/tmpG4o1PQ/test_1.json --streaming --host test_host --username test_user --password test_password --routing-key harvest.start.test.test_search\nuser=kerchner\nautostart=true\nautorestart=true\nstderr_logfile=/tmp/tmpbUl8xl/test_1.err.log\nstdout_logfile=/tmp/tmpbUl8xl/test_1.out.log\n'

======================================================================
FAIL: test_pick_a_port (tests.sfmutils.test_warcprox.WarcedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/home/kerchner/projects/sfm-utils/tests/sfmutils/test_warcprox.py", line 30, in test_pick_a_port
    self.assertEqual(61, sock.connect_ex(('',port)))
AssertionError: 61 != 111

----------------------------------------------------------------------
```

**Comment by justinlittman** [comment]
Regarding warcprox:  I'll create a tag once testing is complete and reference that tag in requirements.txt.

**Comment by justinlittman** [comment]
@kerchner Ready for you to re-try.

**Comment by kerchner** [comment]
:+1:

**Pull request merged**
